// frameworks/solid/src/test-scenarios/scenario-2.jsx
import { createSignal } from "solid-js";

function Cell(props) {
  const [count, setCount] = createSignal(0);
  return (
    <span style={{ "margin-right": "10px" }}>
      outer: {props.value},<br /> inner: {count()}
      <button onClick={() => setCount(count() + 1)}>+</button>
    </span>
  );
}

const Row = (props) => {
  const [count, setCount] = createSignal(0);
  const [offset, setOffset] = createSignal(0);

  const onInput = () => setCount(count() + 1);

  const updateRow = () => setOffset(offset() + 1);

  return (
    <div>
      <div>
        Row: {count()}
        <button className="row-btn-update-children" onClick={updateRow}>
          + children
        </button>
        <button className="row-btn-update-self" onClick={onInput}>
          + parent
        </button>
      </div>
      <div style={{ display: "flex", "margin-bottom": "20px" }}>
        {props.columns.map((column, i) => (
          <Cell key={column.id} value={i + offset()} />
        ))}
      </div>
    </div>
  );
};

const Scenario2 = () => {
  const [numRows, setNumRows] = createSignal(10);
  const [numColumns, setNumColumns] = createSignal(10);
  const [rows, setRows] = createSignal([]);

  const updateRows = (value) => setNumRows(parseInt(value, 10));
  const updateColumns = (value) => setNumColumns(parseInt(value, 10));

  const generate = () => {
    setRows(
      new Array(numRows()).fill(null).map((_, i) => ({
        id: i,
        columns: new Array(numColumns()).fill(null).map((_, y) => ({
          id: `row${i}-col${y}`,
        })),
      }))
    );
  };

  return (
    <div>
      <div>
        <label>Number of rows</label>
        <input
          id="input-rows"
          type="number"
          min="1"
          value={numRows()}
          onChange={(event) => updateRows(event.target.value)}
        />
        <label>Number of columns</label>
        <input
          id="input-columns"
          type="number"
          min="1"
          value={numColumns()}
          onChange={(event) => updateColumns(event.target.value)}
        />
        <button id="btn-generate" onClick={generate}>
          Generate
        </button>
      </div>
      <div>
        {rows().map((row) => (
          <Row key={row.id} columns={row.columns} />
        ))}
      </div>
    </div>
  );
};

export default Scenario2;

// frameworks/angular/src/app/scenario-2/scenario2.component.ts
import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-cell',
  template: `
    <span>
      outer: {{ value }}
      <br />
      inner: {{ count }}
      <button (click)="increment()">+</button>
    </span>
  `,
})
export class CellComponent {
  @Input() value!: number;
  count = 0;

  increment() {
    this.count++;
  }
}

interface Column {
  id: string;
}

@Component({
  selector: 'app-row',
  imports: [CellComponent],
  template: `
    <div>
      <div>
        Row count: {{ count }}
        <button class="row-btn-update-children" (click)="updateRow()">
          + children
        </button>
        <button class="row-btn-update-self" (click)="onInput()">
          + parent
        </button>
      </div>
      <div style="display: flex; flex-direction: row; column-gap: 10px;">
        @for (cell of columns; track cell.id) {
        <app-cell [value]="$index + offset"></app-cell>
        }
      </div>
    </div>
  `,
})
export class RowComponent {
  @Input() columns!: Column[];
  count = 0;
  offset = 0;

  onInput() {
    this.count++;
  }

  updateRow() {
    this.offset++;
  }
}

interface Row {
  id: number;
  columns: { id: string }[];
}

@Component({
  selector: 'app-scenario-2',
  imports: [RowComponent, FormsModule],
  template: `
    <div>
      <div>
        <label>Number of rows</label>
        <input type="number" min="1" [(ngModel)]="numRows" />
        <label>Number of columns</label>
        <input type="number" min="1" [(ngModel)]="numColumns" />
        <button (click)="generate()">Generate</button>
      </div>
      <div style="display: flex; flex-direction: column; row-gap: 20px;">
        @for (row of rows; track row.id) {
        <app-row [columns]="row.columns"></app-row>
        }
      </div>
    </div>
  `,
})
export class Scenario2Component {
  numRows = 10;
  numColumns = 10;
  rows: Row[] = [];

  generate() {
    this.rows = Array(this.numRows)
      .fill(null)
      .map((_, i) => ({
        id: i,
        columns: Array(this.numColumns)
          .fill(null)
          .map((_, y) => ({
            id: `row${i}-col${y}`,
          })),
      }));
  }
}
