// frameworks/angular/src/app/scenario-1/scenario1.component.ts
import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-child',
  template: ` <div>-</div> `,
})
export class Child {}

@Component({
  selector: 'app-child2',
  template: ` <div>{{ id }}</div> `,
})
export class Child2 {
  @Input() id!: number;
}

interface ChildT {
  id: number;
}

@Component({
  selector: 'app-scenario-1',
  imports: [Child2, Child, FormsModule],
  template: `
    <div>
      <div>
        <label>Number of components or elements to create</label>
        <input type="number" min="1" [(ngModel)]="numChildren" />
        <button (click)="generateDynamic()">Generate components</button>
        <button (click)="generateStatic()">Generate static elements</button>
      </div>
      <div>
        <button (click)="remove()">Delete all components</button>
        <button (click)="addOne()">Add one component</button>
        <button (click)="switchType()">Change child component type</button>
      </div>
    </div>
    <div id="content">
      @if (childType === 1) { @for (item of children; track item.id) {
      <app-child></app-child>
      } }@else { @for (item of children; track item.id) {
      <app-child2 [id]="item.id"></app-child2>
      } } @for (item of staticElements; track $index) {
      <div>static</div>
      }
    </div>
  `,
})
export class Scenario1Component {
  numChildren = 0;
  children: ChildT[] = [];
  staticElements: any = [];
  childType = 1;

  addOne() {
    this.children.push({ id: this.children.length });
  }

  remove() {
    this.children = [];
  }

  generateDynamic() {
    this.children = Array(this.numChildren)
      .fill(null)
      .map((_, i) => ({ id: i }));
  }

  generateStatic() {
    this.staticElements = Array(this.numChildren).fill(null);
  }

  onUpdateValue(event: any) {
    this.numChildren = parseInt(event.target.value, 10);
  }

  switchType() {
    this.childType = this.childType === 1 ? 2 : 1;
  }
}

// frameworks/solid/src/test-scenarios/scenario-1.jsx
import { createSignal } from "solid-js";

const Child = () => <div> -</div>;
const Child2 = (props) => <div>{props.id}</div>;

const Scenario1 = () => {
  const [numChildren, setNumChildren] = createSignal(0);
  const [children, setChildren] = createSignal([]);
  const [staticElements, setStaticElements] = createSignal([]);
  const [childType, setChildType] = createSignal(1);

  const addOne = () => setChildren([...children(), { id: children().length }]);

  const remove = () => setChildren([]);

  const generateDynamic = () =>
    setChildren(new Array(numChildren()).fill(null).map((_, i) => ({ id: i })));

  const generateStatic = () =>
    setStaticElements(new Array(numChildren()).fill(null));

  const onUpdateValue = (event) =>
    setNumChildren(parseInt(event.target.value, 10));

  const switchType = () => setChildType(childType() === 1 ? 2 : 1);

  return (
    <>
      <div>
        <div>
          <label>Number of components or elements to create</label>
          <input
            id="input-num-to-create"
            type="number"
            min="1"
            onChange={onUpdateValue}
          />
          <button id="btn-generate-components" onClick={generateDynamic}>
            Generate components
          </button>
          <button id="btn-generate-elements" onClick={generateStatic}>
            Generate static elements
          </button>
        </div>
        <div>
          <button id="btn-delete" onClick={remove}>
            Delete all components
          </button>
          <button id="btn-add-one" onClick={addOne}>
            Add one component
          </button>
          <button id="btn-switch-child-type" onClick={switchType}>
            Change child component type
          </button>
        </div>
      </div>
      <div id="content">
        {children().map((item) =>
          childType() === 1 ? (
            <Child key={item.id} />
          ) : (
            <Child2 key={item.id} id={item.id} />
          )
        )}
        {staticElements().map((_, i) => (
          <div key={i}>static</div>
        ))}
      </div>
    </>
  );
};

export default Scenario1;
