// frameworks/angular/src/app/scenario-3/scenario3.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-node',
  imports: [CommonModule],
  template: `
    <div>
      <ng-container *ngIf="subtreeDepth > 0; else staticNode">
        @for (_ of arr(branchingFactor).fill(1); track $index) {
        <app-node
          [branchingFactor]="branchingFactor"
          [subtreeDepth]="subtreeDepth - 1"
        >
        </app-node>
        }
      </ng-container>

      <ng-template #staticNode>
        <div>
          {{ count }}
          <button class="btn-increment-leaf" (click)="increment()">+</button>
        </div>
      </ng-template>
    </div>
  `,
})
export class NodeComponent {
  @Input() branchingFactor!: number;
  @Input() subtreeDepth!: number;
  count = 0;

  arr = Array;

  increment() {
    this.count++;
  }
}

@Component({
  selector: 'app-node2',
  imports: [CommonModule],
  template: `
    <div>
      <ng-container *ngIf="subtreeDepth > 0; else staticNode">
        @for (_ of arr(branchingFactor).fill(1); track $index) {
        <app-node2
          [branchingFactor]="branchingFactor"
          [subtreeDepth]="subtreeDepth - 1"
        >
        </app-node2>
        }
      </ng-container>

      <ng-template #staticNode>-</ng-template>
    </div>
  `,
})
export class Node2Component {
  @Input() branchingFactor!: number;
  @Input() subtreeDepth!: number;
  arr = Array;
}

@Component({
  selector: 'app-scenario-3',
  imports: [NodeComponent, Node2Component, FormsModule],
  template: `
    <div>
      <label>branching factor</label>
      <input type="number" [(ngModel)]="n" />
      <label>tree depth</label>
      <input type="number" [(ngModel)]="m" />
      <button (click)="generate()">Generate tree</button>
      <button (click)="generateSimple()">Generate static tree</button>
      <div>{{ count }}</div>
      <button (click)="increment()">+ root</button>
      @if (initialized) { @if (nodeType === 1) {
      <div>
        @for (_ of arr(branchingFactor).fill(1); track $index) {
        <app-node
          [branchingFactor]="branchingFactor"
          [subtreeDepth]="treeDepth - 1"
        >
        </app-node>
        }
      </div>
      }@else {
      <div>
        @for (_ of arr(branchingFactor).fill(1); track $index) {
        <app-node2
          [branchingFactor]="branchingFactor"
          [subtreeDepth]="treeDepth - 1"
        >
        </app-node2>
        }
      </div>
      } }
    </div>
  `,
})
export class Scenario3Component {
  n = 3;
  m = 3;
  branchingFactor = 3;
  treeDepth = 3;
  initialized = false;
  count = 0;
  nodeType = 1;
  arr = Array;

  generate() {
    this.initialized = true;
    this.branchingFactor = this.n;
    this.treeDepth = this.m;
  }

  generateSimple() {
    this.nodeType = 2;
    this.initialized = true;
    this.branchingFactor = this.n;
    this.treeDepth = this.m;
  }

  increment() {
    this.count++;
  }
}

// frameworks/solid/src/test-scenarios/scenario-3.jsx
import { createSignal } from "solid-js";

const StaticNode = (props) => (
  <div>
    {props.subtreeDepth > 0 &&
      [...Array(props.branchingFactor)].map((_, i) => (
        <StaticNode
          key={i}
          branchingFactor={props.branchingFactor}
          subtreeDepth={props.subtreeDepth - 1}
        />
      ))}
    -
  </div>
);

const DynamicNode = (props) => {
  const [count, setCount] = createSignal(0);

  const increment = () => {
    setCount(count() + 1);
  };

  return (
    <div>
      {props.subtreeDepth > 0 &&
        [...Array(props.branchingFactor)].map((_, i) => (
          <DynamicNode
            key={i}
            branchingFactor={props.branchingFactor}
            subtreeDepth={props.subtreeDepth - 1}
          />
        ))}
      <div>
        {count}
        <button className="btn-increment-leaf" onClick={increment}>
          +
        </button>
      </div>
    </div>
  );
};

const Scenario3 = () => {
  const [branchingFactor, setBranchingFactor] = createSignal(0);
  const [treeDepth, setTreeDepth] = createSignal(0);
  const [initialized, setInitialized] = createSignal(false);
  const [count, setCount] = createSignal(0);
  const [nodeType, setNodeType] = createSignal(1);

  const onUpdateBranchingFactor = (event) => {
    setBranchingFactor(parseInt(event.target.value, 10));
  };

  const onUpdateTreeDepth = (event) => {
    setTreeDepth(parseInt(event.target.value, 10));
  };

  const generate = () => {
    setNodeType(1);
    setInitialized(true);
  };

  const generateSimple = () => {
    setNodeType(2);
    setInitialized(true);
  };

  const increment = () => {
    setCount(count() + 1);
  };

  return (
    <div>
      <label>branching factor</label>
      <input
        id="input-branching-factor"
        type="number"
        onChange={onUpdateBranchingFactor}
      />
      <label>tree depth</label>
      <input id="input-tree-depth" type="number" onChange={onUpdateTreeDepth} />
      <button id="btn-generate" onClick={generate}>
        Generate tree
      </button>
      <button id="btn-generate-simple" onClick={generateSimple}>
        Generate static tree
      </button>
      <div>{count()}</div>
      <button id="btn-increment-root" onClick={increment}>
        + root
      </button>
      {initialized() && (
        <div>
          {nodeType() === 1
            ? [...Array(branchingFactor())].map((_, i) => (
                <DynamicNode
                  key={i}
                  branchingFactor={branchingFactor()}
                  subtreeDepth={treeDepth() - 1}
                />
              ))
            : [...Array(branchingFactor())].map((_, i) => (
                <StaticNode
                  key={i}
                  branchingFactor={branchingFactor()}
                  subtreeDepth={treeDepth() - 1}
                />
              ))}
        </div>
      )}
    </div>
  );
};

export default Scenario3;
