// frameworks/solid/src/test-scenarios/scenario-4.jsx
import { createSignal } from "solid-js";

import Child from "./Child4";

export default function Scenario4() {
  const [numChildren, setNumChildren] = createSignal(0);
  const [children, setChildren] = createSignal([]);

  const generate = () => {
    setChildren(
      new Array(numChildren()).fill(null).map((_, i) => ({ id: i, value: i }))
    );
  };

  const update = () => {
    setChildren(
      children().map((child) => ({
        ...child,
        value: child.value + 1,
      }))
    );
  };

  const updateRandomChild = () => {
    if (children().length === 0) return;

    const i = Math.floor(Math.random() * children().length);

    // Create a *new* array with the updated child.  This is crucial!
    const updatedChildren = [...children()];
    updatedChildren[i] = {
      ...updatedChildren[i],
      value: updatedChildren[i].value + 1,
    };
    setChildren(updatedChildren);
  };

  const onChange = (event) => {
    setNumChildren(parseInt(event.target.value, 10));
  };

  return (
    <div>
      <div>
        <label>Number of components</label>
        <input
          id="input-components"
          type="number"
          min="1"
          onChange={onChange}
        />
        <button id="btn-generate" onClick={generate}>
          Generate
        </button>
        <button id="btn-update" onClick={update}>
          Update children
        </button>
        <button id="btn-update-single" onClick={updateRandomChild}>
          Update single child
        </button>
      </div>
      {children().map((child) => (
        <Child key={child.id} value={child.value} />
      ))}
    </div>
  );
}

// frameworks/angular/src/app/scenario-4/scenario4.component.ts
import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-child',
  template: `
    <div>
      <span>-</span><span>-</span><span>-</span><span>-</span><span>-</span>
      <span>-</span><span>-</span><span>-</span><span>-</span><span>-</span>
      <span>-</span><span>-</span><span>-</span><span>-</span><span>-</span>
      <span>-</span><span>-</span><span>-</span><span>-</span><span>-</span>
      <span>-</span><span>-</span><span>-</span><span>-</span><span>-</span>
      <span>{{ value }}</span>
      <span>-</span><span>-</span><span>-</span><span>-</span><span>-</span>
      <span>-</span><span>-</span><span>-</span><span>-</span><span>-</span>
      <span>-</span><span>-</span><span>-</span><span>-</span><span>-</span>
      <span>-</span><span>-</span><span>-</span><span>-</span><span>-</span>
      <span>-</span><span>-</span><span>-</span><span>-</span><span>-</span>
    </div>
  `,
})
export class ChildComponent {
  @Input() value!: number;
}

interface Child {
  id: number;
  value: number;
}

@Component({
  selector: 'app-scenario-4',
  imports: [ChildComponent, FormsModule],
  template: `
    <div>
      <div>
        <label>Number of components</label>
        <input type="number" min="1" [(ngModel)]="numChildren" />
        <button (click)="generate()">Generate</button>
        <button (click)="update()">Update children</button>
        <button (click)="updateRandomChild()">Update single child</button>
      </div>
      @for (child of children; track child.id) {
      <app-child [value]="child.value"></app-child>
      }
    </div>
  `,
})
export class Scenario4Component {
  numChildren = 10;
  children: Child[] = [];

  generate() {
    this.children = Array(this.numChildren)
      .fill(null)
      .map((_, i) => ({ id: i, value: i }));
  }

  update() {
    this.children = this.children.map((child) => ({
      ...child,
      value: child.value + 1,
    }));
  }

  updateRandomChild() {
    if (this.children.length === 0) return;

    const i = Math.floor(Math.random() * this.children.length);
    this.children = this.children.map((child, index) => {
      if (index === i) {
        return { ...child, value: child.value + 1 };
      }
      return child;
    });
  }
}
