// frameworks/solid/src/test-scenarios/scenario-1.jsx
import { createSignal } from "solid-js";

const Child = () => <div> -</div>;
const Child2 = (props) => <div>{props.id}</div>;

const Scenario1 = () => {
  const [numChildren, setNumChildren] = createSignal(0);
  const [children, setChildren] = createSignal([]);
  const [staticElements, setStaticElements] = createSignal([]);
  const [childType, setChildType] = createSignal(1);

  const addOne = () => setChildren([...children(), { id: children().length }]);

  const remove = () => setChildren([]);

  const generateDynamic = () =>
    setChildren(new Array(numChildren()).fill(null).map((_, i) => ({ id: i })));

  const generateStatic = () =>
    setStaticElements(new Array(numChildren()).fill(null));

  const onUpdateValue = (event) =>
    setNumChildren(parseInt(event.target.value, 10));

  const switchType = () => setChildType(childType() === 1 ? 2 : 1);

  return (
    <>
      <div>
        <div>
          <label>Number of components or elements to create</label>
          <input
            id="input-num-to-create"
            type="number"
            min="1"
            onChange={onUpdateValue}
          />
          <button id="btn-generate-components" onClick={generateDynamic}>
            Generate components
          </button>
          <button id="btn-generate-elements" onClick={generateStatic}>
            Generate static elements
          </button>
        </div>
        <div>
          <button id="btn-delete" onClick={remove}>
            Delete all components
          </button>
          <button id="btn-add-one" onClick={addOne}>
            Add one component
          </button>
          <button id="btn-switch-child-type" onClick={switchType}>
            Change child component type
          </button>
        </div>
      </div>
      <div id="content">
        {children().map((item) =>
          childType() === 1 ? (
            <Child key={item.id} />
          ) : (
            <Child2 key={item.id} id={item.id} />
          )
        )}
        {staticElements().map((_, i) => (
          <div key={i}>static</div>
        ))}
      </div>
    </>
  );
};

export default Scenario1;

// frameworks/vue/src/components/scenario-1/Scenario1.vue
<template>
  <div>
    <div>
      <label>Number of components or elements to create</label>
      <input
        id="input-num-to-create"
        type="number"
        min="1"
        :value="numChildren"
        @change="onUpdateValue"
      />
      <button id="btn-generate-components" @click="generateComponents">
        Generate components
      </button>
      <button id="btn-generate-elements" @click="generateElements">
        Generate static elements
      </button>
    </div>
    <div>
      <button id="btn-delete" @click="remove">Delete all components</button>
      <button id="btn-add-one" @click="addOne">Add one component</button>
      <button id="btn-switch-child-type" @click="switchType">
        Change child component type
      </button>
    </div>
    <div>
      <template v-if="childType === 1">
        <Child v-for="child in children" :key="child.id" />
      </template>
      <template v-else>
        <Child2 v-for="child in children" :key="child.id" :id="child.id" />
      </template>
      <div v-for="(_, i) in elements" :key="i">static</div>
    </div>
  </div>
</template>

<script>
import Child from "./Child.vue";
import Child2 from "./Child2.vue";

export default {
  components: {
    Child,
    Child2,
  },
  data() {
    return {
      numChildren: 3,
      children: [],
      elements: [],
      childType: 1,
    };
  },
  methods: {
    addOne() {
      this.children.push({ id: this.children.length });
    },
    remove() {
      this.children = [];
    },
    switchType() {
      this.childType = this.childType === 1 ? 2: 1;
    },
    generateComponents() {
      this.children = new Array(this.numChildren)
        .fill(null)
        .map((_, i) => ({ id: i }));
    },
    generateElements() {
      this.elements = new Array(this.numChildren).fill(null);
    },
    onUpdateValue(event) {
      this.numChildren = parseInt(event.target.value, 10);
    },
  },
};
</script>
