// frameworks/solid/src/test-scenarios/scenario-5.jsx
import { createSignal } from "solid-js";

import Node from "./Node5.jsx";

export default function Scenario5() {
  const [branchingFactor, setBranchingFactor] = createSignal(0);
  const [treeDepth, setTreeDepth] = createSignal(0);
  const [initialized, setInitialized] = createSignal(false);
  const [count, setCount] = createSignal(0);
  const [prop, setProp] = createSignal(0);

  const onUpdateBranchingFactor = (event) => {
    setBranchingFactor(parseInt(event.target.value, 10));
  };

  const onUpdateTreeDepth = (event) => {
    setTreeDepth(parseInt(event.target.value, 10));
  };

  const generate = () => {
    setInitialized(true);
  };

  const increment = () => {
    setCount(count() + 1);
  };

  const updateTree = () => {
    setProp(prop() + 1);
  };

  return (
    <div>
      <label>Select branching factor</label>
      <input
        id="input-branching-factor"
        type="number"
        onChange={onUpdateBranchingFactor}
      />
      <label>tree depth</label>
      <input id="input-tree-depth" type="number" onChange={onUpdateTreeDepth} />
      <button id="btn-generate" onClick={generate}>
        Generate tree
      </button>
      <div>{count()}</div>
      <button id="btn-increment-root" onClick={increment}>
        Update root
      </button>
      <button id="btn-update-tree" onClick={updateTree}>
        Update entire tree
      </button>
      {initialized() &&
        [...Array(branchingFactor())].map((_, i) => (
          <div key={i}>
            <Node
              branchingFactor={branchingFactor()}
              subtreeDepth={treeDepth()}
              prop={prop()}
            />
          </div>
        ))}
    </div>
  );
}

// frameworks/vue/src/components/scenario-5/Scenario5.vue
<template>
  <div>
    <label>Select branching factor</label>
    <input
      id="input-branching-factor"
      type="number"
      :value="branchingFactor"
      @change="onUpdateBranchingFactor"
    />
    <label>Select tree depth</label>
    <input
      id="input-tree-depth"
      type="number'"
      :value="treeDepth"
      @change="onUpdateTreeDepth"
    />
    <button id="btn-generate" @click="generate">Generate tree</button>
    <div>{{ count }}</div>
    <button id="btn-increment-root" @click="increment">Update root</button>
    <button id="btn-update-tree" @click="updateTree">Update entire tree</button>
    <div v-if="initialized">
      <Node
        v-for="n in branchingFactor"
        :key="n"
        :branching-factor="branchingFactor"
        :subtree-depth="treeDepth - 1"
        :prop="prop"
      />
    </div>
  </div>
</template>

<script>
import Node from "./Node.vue";

export default {
  components: {
    Node,
  },
  data() {
    return {
      branchingFactor: 0,
      treeDepth: 0,
      initialized: false,
      count: 0,
      prop: 0,
    };
  },
  methods: {
    onUpdateBranchingFactor(event) {
      this.branchingFactor = parseInt(event.target.value, 10);
    },
    onUpdateTreeDepth(event) {
      this.treeDepth = parseInt(event.target.value, 10);
    },
    generate() {
      this.initialized = true;
    },
    increment() {
      this.count += 1;
    },
    updateTree() {
      this.prop += 1;
    },
  },
};
</script>
