// frameworks/solid/src/test-scenarios/scenario-3.jsx
import { createSignal } from "solid-js";

const StaticNode = (props) => (
  <div>
    {props.subtreeDepth > 0 &&
      [...Array(props.branchingFactor)].map((_, i) => (
        <StaticNode
          key={i}
          branchingFactor={props.branchingFactor}
          subtreeDepth={props.subtreeDepth - 1}
        />
      ))}
    -
  </div>
);

const DynamicNode = (props) => {
  const [count, setCount] = createSignal(0);

  const increment = () => {
    setCount(count() + 1);
  };

  return (
    <div>
      {props.subtreeDepth > 0 &&
        [...Array(props.branchingFactor)].map((_, i) => (
          <DynamicNode
            key={i}
            branchingFactor={props.branchingFactor}
            subtreeDepth={props.subtreeDepth - 1}
          />
        ))}
      <div>
        {count}
        <button className="btn-increment-leaf" onClick={increment}>
          +
        </button>
      </div>
    </div>
  );
};

const Scenario3 = () => {
  const [branchingFactor, setBranchingFactor] = createSignal(0);
  const [treeDepth, setTreeDepth] = createSignal(0);
  const [initialized, setInitialized] = createSignal(false);
  const [count, setCount] = createSignal(0);
  const [nodeType, setNodeType] = createSignal(1);

  const onUpdateBranchingFactor = (event) => {
    setBranchingFactor(parseInt(event.target.value, 10));
  };

  const onUpdateTreeDepth = (event) => {
    setTreeDepth(parseInt(event.target.value, 10));
  };

  const generate = () => {
    setNodeType(1);
    setInitialized(true);
  };

  const generateSimple = () => {
    setNodeType(2);
    setInitialized(true);
  };

  const increment = () => {
    setCount(count() + 1);
  };

  return (
    <div>
      <label>branching factor</label>
      <input
        id="input-branching-factor"
        type="number"
        onChange={onUpdateBranchingFactor}
      />
      <label>tree depth</label>
      <input id="input-tree-depth" type="number" onChange={onUpdateTreeDepth} />
      <button id="btn-generate" onClick={generate}>
        Generate tree
      </button>
      <button id="btn-generate-simple" onClick={generateSimple}>
        Generate static tree
      </button>
      <div>{count()}</div>
      <button id="btn-increment-root" onClick={increment}>
        + root
      </button>
      {initialized() && (
        <div>
          {nodeType() === 1
            ? [...Array(branchingFactor())].map((_, i) => (
                <DynamicNode
                  key={i}
                  branchingFactor={branchingFactor()}
                  subtreeDepth={treeDepth() - 1}
                />
              ))
            : [...Array(branchingFactor())].map((_, i) => (
                <StaticNode
                  key={i}
                  branchingFactor={branchingFactor()}
                  subtreeDepth={treeDepth() - 1}
                />
              ))}
        </div>
      )}
    </div>
  );
};

export default Scenario3;

// frameworks/vue/src/components/scenario-3/Scenario3.vue
<template>
  <div>
    <label>branching factor</label>
    <input
      id="input-branching-factor"
      type="number"
      :value="branchingFactor"
      @change="onUpdateBranchingFactor"
    />
    <label>tree depth</label>
    <input
      id="input-tree-depth"
      type="number'"
      :value="treeDepth"
      @change="onUpdateTreeDepth"
    />
    <button id="btn-generate" @click="generate">Generate tree</button>
    <button id="btn-generate-simple" @click="generateSimple">
      Generate sitatic  tree
    </button>
    <div>{{ count }}</div>
    <button id="btn-increment-root" @click="increment"> + root</button>
    <div v-if="initialized">
      <template v-if="nodeType === 1">
        <Node
          v-for="n in branchingFactor"
          :key="n"
          :branching-factor="branchingFactor"
          :subtree-depth="treeDepth - 1"
        />
      </template>
      <template v-else>
        <Node2
          v-for="n in branchingFactor"
          :key="n"
          :branching-factor="branchingFactor"
          :subtree-depth="treeDepth - 1"
        />
      </template>
    </div>
  </div>
</template>

<script>
import Node from "./Node.vue";
import Node2 from "./Node2.vue";

export default {
  components: {
    Node,
    Node2,
  },
  data() {
    return {
      branchingFactor: 3,
      treeDepth: 3,
      initialized: false,
      count: 0,
      nodeType: 1,
    };
  },
  methods: {
    onUpdateBranchingFactor(event) {
      this.branchingFactor = parseInt(event.target.value, 10);
    },
    onUpdateTreeDepth(event) {
      this.treeDepth = parseInt(event.target.value, 10);
    },
    generate() {
      this.initialized = true;
    },
    generateSimple() {
      this.nodeType = this.nodeType == 1 ? 2: 1;
      this.initialized = true;
    },
    increment() {
      this.count += 1;
    },
  },
};
</script>
